[project]
name = "weather-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.1",
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0",
    "fastmcp>=2.11.3",
]
